// Dữ liệu nguồn để seed catalog vào DB (7 mục + 51 dịch vụ như bảng giá hiện tại trên FE).
// Sau khi đã seed, việc thêm/sửa dịch vụ thực hiện từ trang admin (/services).
export const catalogCategories: { name: string; nameEn: string; sortOrder: number }[] = [
  { name: 'Style Thiết Kế', nameEn: 'Designed lash styles', sortOrder: 1 },
  { name: 'Style Tự Nhiên', nameEn: 'Natural lash styles', sortOrder: 2 },
  { name: 'Các dịch vụ khác', nameEn: 'Other services', sortOrder: 3 },
  { name: 'Chăm sóc da', nameEn: 'Nail & skin care', sortOrder: 4 },
  { name: 'Nối móng', nameEn: 'Nail extensions', sortOrder: 5 },
  { name: 'Sơn gel', nameEn: 'Gel polish', sortOrder: 6 },
  { name: 'Design', nameEn: 'Nail design', sortOrder: 7 },
]

export const catalogServices: { category: string; name: string; nameEn: string; price: string; image?: string }[] = [
  { category: 'Style Thiết Kế', name: 'Anime Douyin', nameEn: 'Anime Douyin', price: '400.000', image: '/images/lashes/anime-douyin.jpg' },
  { category: 'Style Thiết Kế', name: 'Mi Đuôi Cá', nameEn: 'Fishtail lashes', price: '400.000', image: '/images/lashes/mi-duoi-ca.jpg' },
  { category: 'Style Thiết Kế', name: 'Foxy', nameEn: 'Foxy', price: '420.000', image: '/images/lashes/foxy.jpg' },
  { category: 'Style Thiết Kế', name: 'Ulzang', nameEn: 'Ulzang', price: '400.000', image: '/images/lashes/ulzang.jpg' },
  { category: 'Style Thiết Kế', name: 'Volum', nameEn: 'Volume', price: '300.000', image: '/images/lashes/volum.jpg' },
  { category: 'Style Thiết Kế', name: 'Katun', nameEn: 'Katun', price: '350.000', image: '/images/lashes/katun.jpg' },
  { category: 'Style Thiết Kế', name: 'Mi Đa Tầng', nameEn: 'Layered lashes', price: '450.000', image: '/images/lashes/mi-da-tang.jpg' },
  { category: 'Style Thiết Kế', name: 'Fox eyes', nameEn: 'Fox eyes', price: '420.000', image: '/images/lashes/fox-eyes.jpg' },
  { category: 'Style Thiết Kế', name: 'Anime', nameEn: 'Anime', price: '400.000', image: '/images/lashes/anime.jpg' },
  { category: 'Style Tự Nhiên', name: 'Classic', nameEn: 'Classic', price: '300.000', image: '/images/lashes/classic.jpg' },
  { category: 'Style Tự Nhiên', name: 'Anime Baby', nameEn: 'Anime Baby', price: '350.000', image: '/images/lashes/anime-baby.jpg' },
  { category: 'Style Tự Nhiên', name: 'Sole', nameEn: 'Sole', price: '350.000', image: '/images/lashes/sole.jpg' },
  { category: 'Các dịch vụ khác', name: 'Uốn mi', nameEn: 'Lash lift', price: '150.000' },
  { category: 'Các dịch vụ khác', name: 'Uốn mi + phủ đen', nameEn: 'Lash lift + black tint', price: '200.000' },
  { category: 'Các dịch vụ khác', name: 'Mi dưới', nameEn: 'Bottom lashes', price: '50.000' },
  { category: 'Các dịch vụ khác', name: 'Tháo Mi', nameEn: 'Lash removal', price: '50.000' },
  { category: 'Các dịch vụ khác', name: 'Dặm mi', nameEn: 'Lash refill', price: '200.000 – 250.000' },
  { category: 'Chăm sóc da', name: 'Cắt da tay', nameEn: 'Manicure cuticle care', price: '30.000/bộ' },
  { category: 'Chăm sóc da', name: 'Cắt da tay (nam)', nameEn: 'Men’s manicure cuticle care', price: '50.000/bộ' },
  { category: 'Chăm sóc da', name: 'Cắt da chân', nameEn: 'Pedicure cuticle care', price: '40.000/bộ' },
  { category: 'Chăm sóc da', name: 'Cắt da chân (nam)', nameEn: 'Men’s pedicure cuticle care', price: '60.000/bộ' },
  { category: 'Chăm sóc da', name: 'Phá sơn gel', nameEn: 'Gel removal', price: '30.000/bộ' },
  { category: 'Chăm sóc da', name: 'Phá gel cứng / móng up / bột', nameEn: 'Hard gel, tip or acrylic removal', price: '50.000/bộ' },
  { category: 'Sơn gel', name: 'Sơn gel', nameEn: 'Gel polish', price: '100.000/bộ' },
  { category: 'Sơn gel', name: 'Sơn gel cao cấp Kaise', nameEn: 'Kaise premium gel', price: '130.000/bộ' },
  { category: 'Sơn gel', name: 'Sơn thạch', nameEn: 'Jelly gel', price: '120.000/bộ' },
  { category: 'Sơn gel', name: 'Sơn thạch cao cấp Kaise', nameEn: 'Kaise premium jelly gel', price: '150.000/bộ' },
  { category: 'Sơn gel', name: 'Sơn mắt mèo cao cấp', nameEn: 'Premium cat eye', price: '160.000/bộ' },
  { category: 'Sơn gel', name: 'Mix nhiều màu', nameEn: 'Multi-color mix', price: '30.000/bộ' },
  { category: 'Sơn gel', name: 'Mix một màu', nameEn: 'Single-color mix', price: '10.000/bộ' },
  { category: 'Sơn gel', name: 'Sơn nhũ', nameEn: 'Shimmer polish', price: '150.000/bộ' },
  { category: 'Sơn gel', name: 'Phủ thêm nhũ, kim tuyến', nameEn: 'Glitter or shimmer add-on', price: '50.000/bộ' },
  { category: 'Sơn gel', name: 'Top trứng cút', nameEn: 'Quail egg top coat', price: '80.000/bộ' },
  { category: 'Nối móng', name: 'Gắn móng giả (Base)', nameEn: 'False nail tips (Base)', price: '120.000/bộ' },
  { category: 'Nối móng', name: 'Fill móng up', nameEn: 'Gel tip fill', price: '80.000/bộ' },
  { category: 'Nối móng', name: 'Nối móng tip + đắp gel', nameEn: 'Tip extensions + gel overlay', price: '290.000/bộ' },
  { category: 'Nối móng', name: 'Fill móng đắp', nameEn: 'Overlay fill', price: '180.000/bộ' },
  { category: 'Nối móng', name: 'Phủ gel + tạo cầu móng', nameEn: 'Gel overlay + nail structure', price: '100.000/bộ' },
  { category: 'Nối móng', name: 'Cứng móng + tạo cầu móng', nameEn: 'Nail strengthening + structure', price: '70.000/bộ' },
  { category: 'Nối móng', name: 'Cứng móng', nameEn: 'Nail strengthening', price: '50.000/bộ' },
  { category: 'Design', name: 'French đầu móng', nameEn: 'French tips', price: '10.000 – 25.000/ngón' },
  { category: 'Design', name: 'Ombre', nameEn: 'Ombre', price: '15.000 – 20.000/ngón' },
  { category: 'Design', name: 'Tráng gương', nameEn: 'Chrome', price: '10.000 – 20.000/ngón' },
  { category: 'Design', name: 'Vẽ gel nổi', nameEn: '3D gel art', price: '10.000 – 50.000/ngón' },
  { category: 'Design', name: 'Vẽ móng, vẽ design', nameEn: 'Nail art and design', price: '5.000 – 35.000/ngón' },
  { category: 'Design', name: 'Vẽ hoạt hình', nameEn: 'Cartoon nail art', price: '35.000 – 60.000/ngón' },
  { category: 'Design', name: 'Nặn nổi thú', nameEn: '3D animal sculpting', price: '25.000 – 60.000/cái' },
  { category: 'Design', name: 'Đính đá, charm', nameEn: 'Rhinestones and charms', price: '5.000 – 60.000/cái' },
  { category: 'Design', name: 'Đắp nhũ, xà cừ, dán line, hoa khô', nameEn: 'Shimmer, shell, line and dried flowers', price: '10.000 – 30.000/ngón' },
  { category: 'Design', name: 'Dán sticker', nameEn: 'Sticker', price: '5.000 – 20.000/cái' },
  { category: 'Chăm sóc da', name: 'Chà gót chân – phục hồi da', nameEn: 'Heel scrub & skin recovery', price: '160.000 – 220.000' },
]
